name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-container:
         - strapi4-sharp-tests-ctn
         - strapi4-postgres-pg-tests-ctn
         - strapi4-postgres-pg-connection-string-tests-ctn
        #  - strapi4-strapi-unit-front-tests-ctn # fail due to sqlite3 install
        #  - strapi4-strapi-unit-back-tests-ctn
    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose build ${{ matrix.test-container }}

      - name: Test
        run: docker-compose up ${{ matrix.test-container }}


  publish:
    runs-on: ubuntu-latest
    needs: tests
    strategy:
      matrix:
        published-container:
         - strapi4-deps
        #  - strapi4-deps-heroku
         - strapi4-quasar2-deps-heroku
    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose build ${{ matrix.published-container }}-ctn

      - name: Test
        run: docker-compose up ${{ matrix.published-container }}-ctn

      - name: Login to docker hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: docker image ls
        run: docker image ls

      - name: Push docker image to docker hub
        run: docker push jclaveau/${{ matrix.published-container }}:latest